# [START runtime]
runtime: nodejs8
handlers:
  - url: /
    static_files: dist/danielclas-cv/index.html
    upload: dist/danielclas-cv/index.html
  - url: /
    static_dir: dist/danielclas-cv
manual_scaling:
  instances: 1
# [END runtime]
